books = [
    [{"main": "gn"}, "gen", "ge", "gn", "gn", "Genesis"],
    [{"main": "ex"}, "exod", "ex", "ex", "Exodus"],
    [{"main": "lv"}, "lev", "lv", "le", "lv", "Leviticus"],
    [{"main": "nm"}, "num", "nm", "nu", "nm", "Numbers"],
    [{"main": "dt"}, "deut", "dt", "de", "du", "dt", "Deuteronomy"],
    [{"main": "js"}, "josh", "jos", "jo", "js", "Joshua"],
    [{"main": "jud"}, "judg", "jdg", "jgs", "jud", "Judges"],
    [{"main": "rt"}, "ruth", "ru", "rt", "Ruth"],
    [{"main": "1sm"}, "1 sam", "1sm", "1sa", "1sm", "1 Samuel"],
    [{"main": "2sm"}, "2 sam", "2sm", "2sa", "2sm", "2 Samuel"],
    [{"main": "1kgs"}, "1 kgs", "1kg", "1ki", "1kgs", "1 Kings"],
    [{"main": "2kgs"}, "2 kgs", "2kg", "2ki", "2kgs", "2 Kings"],
    [{"main": "1ch"}, "1 chr", "1 chron", "1ch", "1ch", "1 Chronicles"],
    [{"main": "2ch"}, "2 chr", "2 chron", "2ch", "2ch", "2 Chronicles"],
    [{"main": "ezr"}, "ezra", "ezr", "ezr", "Ezra"],
    [{"main": "ne"}, "neh", "ne", "ne", "Nehemiah"],
    [{"main": "et"}, "esth", "est", "es", "et", "Esther"],
    [{"main": "job"}, "job", "jb", "job", "Job"],
    [{"main": "ps"}, "os", "pss", "ps", "Psalms"],
    [{"main": "prv"}, "prov", "prv", "pr", "prv", "Proverbs"],
    [{"main": "ec"}, "eccl", "eccles", "ec", "qoh", "ec", "Ecclesiastes"],
    [
        {"main": "so"},
        "song",
        "ss",
        "so",
        "sg",
        "cant",
        "can",
        "so",
        "Song of Songs Canticle of Canticles",
    ],
    [{"main": "is"}, "isa", "is", "is", "Isaiah"],
    [{"main": "jr"}, "jer", "je", "jr", "Jeremiah"],
    [{"main": "lm"}, "lam", "la", "lm", "Lamentations"],
    [{"main": "ez"}, "ezek", "ezk", "ez", "ez", "Ezekiel"],
    [{"main": "dn"}, "dan", "dn", "da", "dn", "Daniel"],
    [{"main": "ho"}, "hos", "ho", "ho", "Hosea"],
    [{"main": "jl"}, "joel", "joe", "jl", "jl", "Joel"],
    [{"main": "am"}, "amos", "am", "am", "Amos"],
    [{"main": "ob"}, "obad", "ob", "ob", "Obadiah"],
    [{"main": "jn"}, "jonah", "jon", "jn", "Jonah"],
    [{"main": "mi"}, "mic", "mi", "mi", "Micah"],
    [{"main": "na"}, "nah", "na", "na", "Nahum"],
    [{"main": "hk"}, "hab", "hb", "hk", "Habakkuk"],
    [{"main": "zp"}, "zeph", "zep", "zp", "Zephaniah"],
    [{"main": "hg"}, "hag", "hg", "hg", "Haggai"],
    [{"main": "zc"}, "zech", "zec", "zc", "Zechariah"],
    [{"main": "ml"}, "mal", "ml", "ml", "Malachi"],
    [{"main": "mt"}, "matt", "mat", "mt", "mt", "Matthew"],
    [{"main": "mk"}, "mark", "mar", "mk", "mk", "Mark"],
    [{"main": "lk"}, "luke", "lk", "lu", "lk", "Luke"],
    [{"main": "jo"}, "john", "jn", "jo", "jo", "John"],
    [{"main": "act"}, "acts", "ac", "act", "Acts of the Apostles"],
    [{"main": "rm"}, "rom", "rm", "ro", "rm", "Romans"],
    [{"main": "1co"}, "1 cor", "1 co", "1c", "1co", "1 Corinthians"],
    [{"main": "2co"}, "2 cor", "2 co", "2c", "2co", "2 Corinthians"],
    [{"main": "gl"}, "gal", "ga", "gl", "Galatians"],
    [{"main": "eph"}, "eph", "ep", "eph", "Ephesians"],
    [{"main": "ph"}, "phil", "php", "ph", "Philippians"],
    [{"main": "cl"}, "col", "co", "cl", "Colossians"],
    [{"main": "1ts"}, "1 thess", "1 thes", "1th", "1ts", "1 Thessalonians"],
    [{"main": "2ts"}, "2 thess", "2 thes", "2th", "2ts", "2 Thessalonians"],
    [{"main": "1tm"}, "1 tim", "1 tm", "1 ti", "1t", "1tm", "1 Timothy"],
    [{"main": "2tm"}, "2 tim", "2 tm", "2 ti", "2t", "2tm", "2 Timothy"],
    [{"main": "tt"}, "titus", "tit", "ti", "tt", "Titus"],
    [{"main": "phm"}, "phlm", "philem", "phm", "phm", "Philemon"],
    [{"main": "hb"}, "heb", "he", "hb", "Hebrews"],
    [{"main": "jm"}, "jas", "ja", "jm", "James"],
    [{"main": "1pe"}, "1 pet", "1 pt", "1p", "1pe", "1 Peter"],
    [{"main": "2pe"}, "2 pet", "2 pt", "2p", "2pe", "2 Peter"],
    [{"main": "1jo"}, "1 john", "1 jn", "1 jo", "1j", "1jo", "1 John"],
    [{"main": "2jo"}, "2 john", "2 jn", "2 jo", "2j", "2jo", "2 John"],
    [{"main": "3jo"}, "3 john", "3 jn", "3 jo", "3j", "3jo", "3 John"],
    [{"main": "jd"}, "jude", "ju", "jd", "Jude"],
    [{"main": "re"}, "rev", "re", "rv", "apoc", "ap", "re", "Revelation Apocalypse"],
]
