services:
  api:
    build: .
    ports:
      - "8000:8000"
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "5900:5900"
    privileged: true
    shm_size: 2g
    hostname: chrome
    environment:
      - VNC_NO_PASSWORD=true
