version: '3'
services:
  api:
    image: python:3.12
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "${SERVER_PORT:-8000}:${SERVER_PORT:-8000}"
    command: 
      - sh 
      - -c 
      - "pip install --no-cache-dir -r requirements.txt && \
        python -u server.py"
    env_file:
      - .env
    environment:
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      SMTP_SERVER: "${SMTP_SERVER}"
      SMTP_PORT: "${SMTP_PORT:-587}"
      SERVER_PORT: "${SERVER_PORT:-8000}"
      DEBUG: "${DEBUG:-true}"

  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4442:4444"
      - "5900:5900"
    privileged: true
    shm_size: 2g
    hostname: chrome
    environment:
      - VNC_NO_PASSWORD=true
