version: '3'
services:
  api:
    image: python
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: 
      - sh 
      - -c 
      - "pip install --no-cache-dir -r requirements.txt && \
        python -u server.py"
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4442:4444"
      - "5900:5900"
    privileged: true
    shm_size: 2g
    hostname: chrome
    environment:
      - VNC_NO_PASSWORD=true
